server:
  port: 8585
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 789

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 735884143f333bfc5110
            clientSecret:  80dc5102c243214ee9343294487820f6e303e4ef
            scope:
              - email
              - profile

          google:
            clientId: 466465211256-9802v7udg12a3kurmbp6ur2ttt7pfhop.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile